name: "Pesandínho"
description: "Um app pra acompanhar o peso"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  flutter_localizations:
    sdk: flutter
  drift: ^2.14.1
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.21
  fl_chart: ^0.68.0
  csv: ^6.0.0
  googleapis: ^12.0.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.4
  path: ^1.9.0
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  file_picker: ^8.0.3
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.1
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
